---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-env
data:
  app.port: "8080"
  app.host: 0.0.0.0
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-env-pod
spec:
  containers:
  - name: demoapp
    image: ikubernetes/demoapp:v1.0
    env:
    - name: PORT
      valueFrom:
        configMapKeyRef:
          name: cm-env
          key: app.port
    - name: HOST
      valueFrom:
        configMapKeyRef:
          name: cm-env
          key: app.host
