---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-envfrom
data:
  PORT: "8080"
  HOST: 0.0.0.0
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-envfrom-pod
spec:
  containers:
  - name: demoapp
    image: ikubernetes/demoapp:v1.0
    envFrom:
    - configMapRef:
        name: cm-envfrom
        optional: false
