---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=  # echo -n "admin" | base64
  password: YWRtaW4zMjE= # echo -n "admin321" | base64
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-pod
    image: busybox
    command: ["/bin/sh", "-c", "env"]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username

    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
