
# kubectl create secret docker-registry reg.linux.io --docker-server=reg.linux.io --docker-username=admin --docker-password=Harbor12345 --docker-email="example@gmail.com"
# kubectl create secret generic reg.linux.io  --from-file=.dockerconfigjson=/root/.docker/config.json --type=kubernetes.io/dockerconfigjson

apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  hostAliases:
  - ip: "192.168.1.219"
    hostnames:
    - "reg.linux.io"
  containers:
  - name: myapp
    image: reg.linux.io/baseimages/myapp:v1
    command: ["/bin/sh", "-c", "sleep 5600"]
  imagePullSecrets:
  - name: reg.linux.io
