apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
type: kubernetes.io/dockerconfigjson
data:
   #这里添加加密后的密钥
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJyZWcubGludXguaW8iOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2U0dGeVltOXlNVEl6TkRVPSIKCQl9Cgl9Cn0=

# 
