---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - "/bin/sh"
        - "-c"
        - "while true; do echo $(date) >> /tmp/time.html;sleep 3;done"
        volumeMounts:
        - name: share-volume
          mountPath: /tmp
      - name: nginx
        image: nginx:1.15.12-alpine
        volumeMounts:
        - name: share-volume
          mountPath: /usr/share/nginx/html

      volumes:
        - name: share-volume
          emptyDir: {}





