---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        worker-by: nginx
      containers:
      - name: nginx
        image: nginx:1.15.12-alpine
        env:
          - name: TZ
            value: Asia/Shanghai
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html  

      volumes:
        - name: html
          hostPath:
            path: /data





