apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity
spec:
  replicas: 8
  selector: 
    matchLabels:
      k8s-app: myapp
  template:
    metadata:
      labels:
        k8s-app: myapp
    spec:
      containers:
      - name: myapp
        image: ikubernetes/myapp:v1
        ports:
        - name: http
          containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - kubeadm-master-01
                - kubeadm-worker-01
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: ssd
                operator: In
                values:
                - "true"
