---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: myapp
      k8s-ver: v1
  template:
    metadata:
      labels: 
        k8s-app: myapp
        k8s-ver: v1
    spec:
      containers:
      - name: myapp
        image: ikubernetes/myapp:v1
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-clusterip
spec:
  type: ClusterIP
  selector:
    k8s-app: myapp
    k8s-ver: v1
  ports:
  - port: 80
    targetPort: 80



