apiVersion: v1
kind: Pod
metadata:
  name: nginx-cmd
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.15.12-alpine
    ports:
    - name: http
      protocol: TCP
      containerPort: 80
    command: ['/bin/sh', '-c']
    args: ['while true;do echo "$(date)";sleep 3;done']
