apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  initContainers:
  - name: initc
    image: busybox
    command: 
    - wget
    - -O
    - /tmp/index.html
    - http://www.baidu.com
    volumeMounts:
    - name: tempdir
      mountPath: /tmp
  containers:
  - name: nginx
    image: nginx:1.15.12-alpine
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      protocol: TCP
      containerPort: 80
    volumeMounts:
    - name: tempdir
      mountPath: /usr/share/nginx/html
  volumes:
  - name: tempdir
    emptyDir: {}
