apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.15.12-alpine
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      protocol: TCP
      containerPort: 80
    command:
      - sh
      - -c
      - sleep 10; nginx -g "daemon off;"
    startupProbe:
      httpGet:
        port: 80
        path: index.html
      initialDelaySeconds: 10
      periodSeconds: 2
      failureThreshold: 2
      successThreshold: 1
    readinessProbe:
      exec:
        command: ["/bin/sh", "-c", "echo 'Hello Test' > /usr/share/nginx/html/index.html"]
      periodSeconds: 2
      failureThreshold: 2
      successThreshold: 1
      initialDelaySeconds: 3
  restartPolicy: OnFailure

