apiVersion: apps/v1
kind: Deployment
metadata:
   name: myapp
   namespace: default
   labels:
     app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
     metadata:
        labels:
          app: myapp
     spec:
       containers:
       - name: myapp
         image: ikubernetes/myapp:v1
         ports:
         - name: http
           protocol: TCP
           containerPort: 80

         resources:
           requests: 
               memory: 50Mi
               cpu: 50m
