apiVersion: batch/v1
kind: Job
metadata:
  name: busybox-job
spec:
  activeDeadlineSeconds: 20
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: busybox
        image: busybox
        command:
        - "bin/sh"
        - "-c"
        - "for i in 9 8 7 6 5 4 3 2 1;do sleep 1 ;echo $i ;done"
