apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp
  namespace: default
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 10
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
---

apiVersion: apps/v1
kind: Deployment
metadata:
   name: myapp
   namespace: default
   labels:
     app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
     metadata:
        labels:
          app: myapp
     spec:
       containers:
       - name: myapp
         image: ikubernetes/myapp:v1
         ports:
         - name: http
           protocol: TCP
           containerPort: 80

         resources:
           requests:
               memory: 50Mi
               cpu: 50m

